FROM golang:1.26-bookworm AS builder

ARG GOPROXY=https://goproxy.cn,https://proxy.golang.org,direct
ARG SING_BOX_VERSION=latest
ARG SING_BOX_BUILD_TAGS="with_v2ray_api with_quic with_grpc with_wireguard with_utls with_acme with_clash_api"
ENV GOPROXY=${GOPROXY}
ENV CGO_ENABLED=0

RUN go install -trimpath -ldflags="-s -w" -tags "$SING_BOX_BUILD_TAGS" github.com/sagernet/sing-box/cmd/sing-box@"$SING_BOX_VERSION"

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/bin/sing-box /usr/local/bin/sing-box

EXPOSE 8443 8444 8445 9090
ENTRYPOINT ["/usr/local/bin/sing-box"]
